### ISSUE TITLE
Questions about the roadmap

### ISSUE THREAD

**Issue by FabioPinheiro** [IDunion/SD-JWT-Kotlin#10]
Would it be possible to have more visibility about the roadmap map of this project?

More specifically:

---
On the readme it's mentioned
> Up to date with draft version: [04](https://drafts.oauth.net/oauth-selective-disclosure-jwt/draft-ietf-oauth-selective-disclosure-jwt.html)
Is this correct? if so what is a plan to update to the draft version 7?

I'm asking because the [TypeScript version](https://github.com/openwallet-foundation-labs/sd-jwt-js) seems to be following the latest draft version.

---

I see there is a version of a snapshot release of version 0.1.0.
What is the time frame to make it official (and release on the maven central)?

**Comment by fabian-hk** [comment]
Sorry for the late reply. This project is no longer maintained. If you are interested in maintaining this project, please contact me.
