### ISSUE TITLE
extend the interface to accept external instance of a verification service via an interface

### ISSUE THREAD

**Issue by markuskreusch** [IDunion/SD-JWT-Kotlin#7]
This is a similar problem as #5 but for verification. Currently the keys used to verify must be known before the verifyPresentation method is invoked. In some cases the required information about the issuer key is encoded in the presentation itself (if x5c is used or if the lookup like the one defined in https://www.ietf.org/archive/id/draft-terbu-oauth-sd-jwt-vc-00.html#name-jwt-issuer-metadata-respons is required). This prohibits the keys to be known in advance unless the caller parses the presentation by himself and then invokes the library. Parsing should be done only once and only by the library IMHO.

To support the related standards it is thus required to use an interface for verification, something like:

```kotlin
interface Verifier {
    fun verifier(jwt: SignedJWT): JWSVerifier?
}
```

This, together with a default verifier implementing the logic currently in the library, verifying by a map of iss-values to JWKs, will allow for a more flexible verification process.

**Comment by fabian-hk** [comment]
This sounds like a useful feature. If this is important to you, please feel free to open a pull request.
